### PR TITLE
Term::ReadLine::Perl is useful in the perl debugger

### PR DESCRIPTION
**Pull request by dbolser-ebi**
As advised here: http://www.perlmonks.org/?node_id=838813 and elsewhere.

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
I think I'm doing this right! (Reading how to do it here: https://www.ebi.ac.uk/seqdb/confluence/display/ENS/Requesting+New+Perl+Module+Dependencies)

We have Term::ReadLine, but not Term::ReadLine::Perl. WIthout it, the perl debugger is essentially broken.

**Review by avullo — DISMISSED** [review]
I would put it as 'recommends' as this is not a requirement for the installation. The general user is not interested in the gentle art of (e!) debugging :)

**Comment by dbolser-ebi** [comment]
Sorry, I don't really know about cpan files (just copied what I saw). However, can't you make a similar argument about everything in perl_dev?

**Comment by dbolser-ebi** [comment]
Thinking about it, this is for me, so I can use the debugger... Does that mean it should be in a private cpan file?

**Comment by avullo** [comment]
Pardon, what do you mean by perl_dev?
Anyway, I'm not convinced this should be mentioned as a dependency. As you point out, if you want to be able to use the debugger, this goes beyond the installation of the e! API and the user takes the action that he/she considers most appropriate for this kind of activity.
Maybe it's because it's Friday, but please explain exactly what you mean by private cpan file.

**Comment by muffato** [comment]
I agree with @dbolser-ebi . This _perl_dev_ cpanfile was not created for dependencies, but for useful development-related modules that we need on the EBI farm. Dependencies of the APIs are still track in each API's cpanfile

**Comment by avullo** [comment]
Ok, I wasn't aware of this particular cpanfile. Sounds like the right target.

**Comment by dbolser-ebi** [comment]
To be honest, I don't know what I mean by "private cpan file" ;-)

I'm just reading this:
https://www.ebi.ac.uk/seqdb/confluence/display/ENS/Requesting+New+Perl+Module+Dependencies#RequestingNewPerlModuleDependencies-AddingaPrivatecpanfile

**Comment by avullo** [comment]
Fair enough :)
Shall I then assume you're gonna make a request to update perl_dev and then close this one?

**Comment by avullo** [comment]
Sorry my bad, I'm confused this morning. It appears you've done the right thing and I'm not reviewing as I should.

**Comment by dbolser-ebi** [comment]
Thanks. When can I expect this to turn up when I hit, "source /nfs/software/ensembl/latest/envs/basic.sh"? i.e. is it a continuous build, or do I have to wait for another major 'update'?

Thanks,

**Comment by muffato** [comment]
Hi @dbolser-ebi . You need to ask someone on the #farm channel to reinstall the software package

**Pull request merged**
